Adding Functionality for Service Principal Authentication
ezwiefel/azure-databricks-api pull request #9
Opened 2020-04-13 22:35 UTC by MrAlexPeacock

Sorry first PR had an issue in the README

2020-06-23 14:37 UTC, ezwiefel requested changes
@MrAlexPeacock - Apologies on the delay in reviewing this. I'm running a few tests now on my end, but one comment that I wanted to send along while I do that.

Thanks for contributing! Overall, this looks really good.

2020-06-23 14:37 UTC, ezwiefel commented on azure_databricks_api/__sp_auth.py
> +        application_id = '2ff814a6-3304-4ab8-85cb-cd0e6f879c1d'
Could you promote this to a class attribute and include a comment (with link) on where the application_id came from?

2020-06-23 14:41 UTC, MrAlexPeacock commented
The right way to do this is probably msal. But there's a trade-off to making that a dependency. What are your thoughts there?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
From: Erik Zwiefel <notifications@github.com>
Sent: Tuesday, June 23, 2020 10:37:26 AM
To: ezwiefel/azure-databricks-api <azure-databricks-api@noreply.github.com>
Cc: Alexander Peacock <alex@alexanderpeacock.com>; Mention <mention@noreply.github.com>
Subject: Re: [ezwiefel/azure-databricks-api] Adding Functionality for Service Principal Authentication (#9)


@ezwiefel requested changes on this pull request.

@MrAlexPeacock<https://github.com/MrAlexPeacock> - Apologies on the delay in reviewing this. I'm running a few tests now on my end, but one comment that I wanted to send along while I do that.

Thanks for contributing! Overall, this looks really good.

________________________________

In azure_databricks_api/__sp_auth.py<https://github.com/ezwiefel/azure-databricks-api/pull/9#discussion_r444272706>:

> @@ -0,0 +1,35 @@
+import requests
+
+
+class ServicePrincipalAuth(object):
+
+    def __init__(self, **kwargs):
+        self._tenant_id = kwargs.pop('tenant_id')
+        self._client_id = kwargs.pop('client_id')
+        self._client_secret = kwargs.pop('client_secret')
+        self._databricks_resource_id = kwargs.pop('databricks_resource_id')
+
+    def authenticate(self):
+        auth_headers = {'Content-Type': "application/x-www-form-urlencoded"}
+        application_id = '2ff814a6-3304-4ab8-85cb-cd0e6f879c1d'


Could you promote this to a class attribute and include a comment (with link) on where the application_id came from?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ezwiefel/azure-databricks-api/pull/9#pullrequestreview-435847096>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAT34V5NM2A24BFCLVBKNMDRYC42NANCNFSM4MHI7IAA>.

2020-06-23 14:56 UTC, ezwiefel commented
I agree that it would be the way to get. I definitely hear you on taking that dependency, but in this case, I think it makes sense to use `msal`

2020-06-23 14:57 UTC, MrAlexPeacock commented
Sounds good. I’ll put that together in the next couple of days.

From: Erik Zwiefel <notifications@github.com>
Sent: Tuesday, June 23, 2020 10:57 AM
To: ezwiefel/azure-databricks-api <azure-databricks-api@noreply.github.com>
Cc: Alexander Peacock <alex@alexanderpeacock.com>; Mention <mention@noreply.github.com>
Subject: Re: [ezwiefel/azure-databricks-api] Adding Functionality for Service Principal Authentication (#9)


I agree that it would be the way to get. I definitely hear you on taking that dependency, but in this case, I think it makes sense to use msal

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ezwiefel/azure-databricks-api/pull/9#issuecomment-648217418>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAT34V6XJ4JC4XITTGQTWOTRYC7CJANCNFSM4MHI7IAA>.

2020-06-25 23:11 UTC, closed without merging

2020-06-28 20:21 UTC, ezwiefel commented
@MrAlexPeacock - I renamed the `master` branch to `main`... and apparently it had the effect of closing this PR. That's the only reason it was closed. 

If you look at the `main` branch, I've also added some testing and CI/CD capabilities.